name: Windows

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        config: [Release]
        compiler: [msvc]
        experimental: [false]

    name: ${{ matrix.config }}-${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0

      - name: Conan - Create default profile
        run: conan profile new default --detect

      - name: Conan - Profile
        run: type C:\Users\runneradmin\.conan\profiles\default

      - name: Conan - Set runtime
        run: conan profile update settings.compiler.runtime=MD default

      - name: Conan - Install dependencies
        run: conan install . -s build_type=${{ matrix.config }} --install-folder=${{github.workspace}}/build --build missing

      - name: CMake Generation
        shell: cmd
        run: |
            cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }}
      - name: Build Project
        working-directory: ./build
        shell: cmd
        run: |
          cmake --build . --config ${{ matrix.config }} -j2

      - name: Compress artifacts
        run: |
          Compress-Archive -Path ${{github.workspace}}/build/bin/*.* -DestinationPath ${{github.workspace}}/build.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{github.workspace}}/build.zip
          name: release-bin-win-x64_${{github.sha}}